openapi: 3.0.1
info:
  title: Swagger Master Integration
  description: api for master integration
    in the swagger-3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: http://localhost.swagger.io/api
paths:
  /enroll:
    post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: postEnroll
      requestBody:
        description: Pet to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enroll'
        required: true
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      x-codegen-request-body-name: pet

  /addMappingRecords:
    post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: addPet
      requestBody:
        description: Pet to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enroll'
        required: true
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enroll'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      x-codegen-request-body-name: pet
  /pets:
    post:
      description: Creates a new pet in the store.
      requestBody:
        description: Pet to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enroll'
        required: true
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enroll'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      x-codegen-request-body-name: pet

components:
  schemas:
    Enroll:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cpf:
          type: integer
          format: int64
        name:
          type: string


    ErrorModel:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string